name: Deploy to Ontology to GitHub Pages
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  push:
    branches: ["main", "master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "zulu"

      - name: Compile ontology modules using rdfx
        run: |
          pip install rdfx
          bash ./build-development.sh

      - name: Provision Widoco
        run: "sudo /bin/sh -c 'wget -O /usr/local/bin/widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.17/java-17-widoco-1.4.17-jar-with-dependencies.jar'"
      - name: Run Widoco
        run: java -jar /usr/local/bin/widoco.jar -ontFile development/merged.ttl -outFolder development/ontology -rewriteAll -webVowl

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          force_orphan: true
          publish_dir: ./development/ontology
          destination_dir: development
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
